### ISSUE TITLE
Stuff not generating

### ISSUE THREAD

**Issue by KluSim** [luboslenco/add_mesh_LowPolyFactory#2]
Multiple objects result in an error when trying to create them via shift-a<mesh<lowpoly
Terrain: a flat plane appears with this console error:
```
Traceback (most recent call last):
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\LowPolyFactory.py", line 363, in invoke
    self.execute(context)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\LowPolyFactory.py", line 359, in execute
    self, context, add_mesh_terrain.get_options(context))
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\createTerrainObject.py", line 66, in create_terrain_object
    terrain, noise_origin = create_terrain(context, prefs)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\createTerrainObject.py", line 46, in create_terrain
    make_vertex_colors(me, colors_from, colors_to, prefs)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\utils.py", line 208, in make_vertex_colors
    color_layer.data[i].color = col
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 4 items, not 3

location: <unknown location>:-1

location: <unknown location>:-1
```
Water: Flat plane appears and this in the console:
```
location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\LowPolyFactory.py", line 414, in invoke
    self.execute(context)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\LowPolyFactory.py", line 410, in execute
    self, context, add_mesh_water.get_options(context))
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\createWaterObject.py", line 64, in create_water_object
    water, noise_origin = create_water(context, prefs)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\createWaterObject.py", line 46, in create_water
    make_vertex_colors(me, colors_from, colors_to, prefs)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\utils.py", line 208, in make_vertex_colors
    color_layer.data[i].color = col
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 4 items, not 3

location: <unknown location>:-1

location: <unknown location>:-1
```
rock: rock appears with this in the console:
```
location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\LowPolyFactory.py", line 67, in invoke
    self.execute(context)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\LowPolyFactory.py", line 63, in execute
    add_mesh_rock.get_options(context))
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\createRockObject.py", line 57, in create_rock_object
    rock, noise_origin = create_rock(context, prefs)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\createRockObject.py", line 39, in create_rock
    make_vertex_colors(me, colors_from, colors_to, prefs)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\add_mesh_LowPolyFactory\utils.py", line 208, in make_vertex_colors
    color_layer.data[i].color = col
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 4 items, not 3

location: <unknown location>:-1
```
Checked all objects, some of them appear, others don't and all create very similar looking messages in the console

**Comment by luboslenco** [comment]
Sorry no plans for update.
